name: JavaScript

on:
  push:
    branches: ['main']
    paths: ['codes/javascript/**/*.js']
  pull_request:
    branches: ['main']
    paths: ['codes/javascript/**/*.js']
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 24.x
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Run JavaScript Code
        run: deno run -A codes/javascript/test_all.js
